import type { SettingsEntry } from "../types";

/** Settings catalog entries — account section. */
export const ACCOUNT_ENTRIES: readonly SettingsEntry[] = [
  // ── account ──
  {
    id: "account.official",
    section: "account",
    tab: "official",
    anchorId: "settings-anchor-account-official",
    labelKey: "settings.tabOfficial",
    descKeys: [
      "settings.tabOfficialHint",
      "account.signedIn",
      "account.loginOauth",
      "account.loginDevice",
      "account.logout",
      "account.subscription",
      "account.quota",
      "account.profiles",
      "account.manageAccounts",
      "account.addAccount",
      "account.importChat",
      "account.profilesAnother",
    ],
    keywords: [
      "login",
      "oauth",
      "supergrok",
      "quota",
      "account",
      "add account",
      "switch account",
      "mlid",
    ],
  },
  {
    id: "account.callLogs",
    section: "account",
    tab: "official",
    anchorId: "settings-anchor-account-callLogs",
    labelKey: "account.callLogs",
    descKeys: [
      "account.callLogsEmpty",
      "account.callLogsImportHint",
      "account.callLogsImportListed",
      "settings.cliSessionsImportOpen",
      "settings.cliSessions",
    ],
    keywords: [
      "import session",
      "cli sessions",
      "recent sessions",
      "import listed",
      "grok build",
      "导入会话",
      "匯入工作階段",
    ],
  },
  {
    id: "account.providers",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-account-providers",
    labelKey: "settings.tabProviders",
    descKeys: [
      "settings.tabProvidersHint",
      "prov.appendPromptHint",
      "prov.supportsVisionHint",
      "prov.mode.grokBuildProxyHint",
    ],
    keywords: [
      "provider",
      "relay",
      "custom api",
      "base url",
      "soft respawn",
      "live apply",
      "grok build proxy",
      "native search",
      "supports_backend_search",
      // Per-channel appended system-prompt rules live in the provider editor.
      "append prompt",
      "system prompt",
      "rules",
      "vision",
      "image",
      "看图",
      "看圖",
      "识图",
      "識圖",
      "中转",
      "中轉",
      "提供商",
      "供應商",
      "原生搜索",
      "原生搜尋",
      "追加提示词",
      "追加提示詞",
      "提示词注入",
      "提示詞注入",
      "extra headers",
      "custom headers",
      "user-agent",
      "originator",
      "x-api-key",
      "自定义请求头",
      "自訂請求標頭",
    ],
  },
  {
    id: "account.providers.extraHeaders",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-prov-extra-headers",
    labelKey: "prov.extraHeaders",
    descKeys: ["prov.extraHeadersHint"],
    keywords: [
      "extra headers",
      "custom headers",
      "user-agent",
      "originator",
      "x-api-key",
      "agentrouter",
      "anyrouter",
      "自定义请求头",
      "自訂請求標頭",
      "請求頭",
    ],
  },
  {
    id: "account.providers.supportsVision",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-prov-supports-vision",
    labelKey: "prov.supportsVision",
    descKeys: ["prov.supportsVisionHint"],
    keywords: [
      "vision",
      "image_url",
      "see images",
      "multimodal",
      "看图",
      "看圖",
      "识图",
      "識圖",
    ],
  },
  {
    id: "account.providers.mode",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-provider-mode",
    labelKey: "prov.mode",
    descKeys: [
      "prov.mode.genericHint",
      "prov.mode.grokBuildProxyHint",
      "prov.mode.grokBuildProxyUnsupported",
    ],
    keywords: [
      "provider mode",
      "grok build proxy",
      "native relay",
      "native search",
      "supports_backend_search",
      "原生兼容",
      "原生相容",
      "原生搜索",
      "原生搜尋",
    ],
  },
  {
    id: "account.officialApiKey",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-official-key",
    labelKey: "prov.officialApiKey",
    descKeys: ["prov.officialVoiceHint", "prov.officialDesc"],
    keywords: [
      "api key",
      "xai",
      "official key",
      "voice",
      "speech",
      "stt",
      "dictation",
      "语音",
      "語音",
      "听写",
    ],
  },
  {
    id: "account.extras",
    section: "account",
    tab: "extras",
    anchorId: "settings-anchor-account-extras",
    labelKey: "settings.tabExtras",
    descKeys: ["settings.tabExtrasHint"],
    keywords: [
      "extras",
      "拓展",
      "official tools",
      "inject",
      "official-aux",
      "官方工具",
    ],
  },
  {
    id: "account.officialAuxInject",
    section: "account",
    tab: "extras",
    anchorId: "settings-anchor-official-aux-inject",
    labelKey: "prov.officialAuxInject",
    descKeys: [
      "prov.officialAuxInjectDesc",
      "prov.officialAuxInjectDisabled",
      "prov.officialAuxWithUserMcp",
      "prov.officialAuxWithUserMcpDesc",
    ],
    keywords: [
      "official aux",
      "inject tools",
      "x_keyword_search",
      "web_search",
      "vision",
      "official-aux",
      "官方工具",
      "注入",
      "x搜索",
      "imagine",
      "image_gen",
      "画图",
      "custom only",
      "第三方",
      "MCP",
      "拓展",
    ],
  },
];
