import type { SettingsEntry } from "../types";

/** Settings catalog entries — appearance section. */
export const APPEARANCE_ENTRIES: readonly SettingsEntry[] = [
  // ── appearance · theme ──
  {
    id: "appearance.theme",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-theme",
    labelKey: "settings.theme",
    descKeys: [
      "settings.themeDesc",
      "settings.themeSystem",
      "settings.themeLight",
      "settings.themeDark",
    ],
    keywords: ["theme", "dark", "light", "system", "auto", "跟随系统"],
  },
  {
    id: "appearance.themeSchedule",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-themeSchedule",
    labelKey: "settings.themeSchedule",
    descKeys: [
      "settings.themeScheduleDesc",
      "settings.themeScheduleLightFrom",
      "settings.themeScheduleDarkFrom",
      "settings.themeSchedule.nextSwitch",
      "settings.themeSchedule.nextSwitchTomorrow",
      "settings.themeSchedule.invalidEqual",
      "settings.themeSchedule.invalidTimes",
      "settings.themeSchedule.inactivePref",
    ],
    keywords: [
      "schedule",
      "timed",
      "auto theme",
      "light from",
      "dark from",
      "next switch",
      "clock",
      "定时",
      "定時",
      "按时切换",
      "按時切換",
      "浅色开始",
      "深色开始",
      "下次切换",
      "下次切換",
    ],
  },
  {
    id: "appearance.skin",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-skin",
    labelKey: "settings.skin",
    descKeys: ["settings.skinDesc"],
    keywords: ["skin", "color pack", "accent"],
  },
  {
    id: "appearance.wallpaper",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-wallpaper",
    labelKey: "settings.wallpaper",
    descKeys: [
      "settings.wallpaperDesc",
      "settings.wallpaperScrim",
      "settings.wallpaperScrimDesc",
      "settings.wallpaperFromX",
      "settings.wallpaperImagine",
    ],
    keywords: [
      "wallpaper",
      "background",
      "scrim",
      "x",
      "twitter",
      "imagine",
      "背景",
      "壁纸",
    ],
  },
  {
    id: "appearance.skinPresets",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-skin-presets",
    labelKey: "settings.skinPresets.title",
    descKeys: ["settings.skinPresets.desc"],
    keywords: [
      "preset",
      "skin pack",
      "grokskin",
      "export",
      "import",
      "外观预设",
      "外觀預設",
      "皮肤包",
    ],
  },
  {
    id: "appearance.skinCatalog",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-skin-catalog",
    labelKey: "settings.skinCatalog.browse",
    descKeys: ["settings.skinCatalog.desc"],
    keywords: [
      "catalog",
      "theme store",
      "download",
      "仓库",
      "倉庫",
      "主题",
    ],
  },
  {
    id: "appearance.skinSources",
    section: "appearance",
    tab: "theme",
    anchorId: "settings-anchor-skin-sources",
    labelKey: "settings.skinCatalog.manageSources",
    descKeys: ["settings.skinCatalog.sourcesDesc"],
    keywords: [
      "source",
      "catalog source",
      "https",
      "源",
      "來源",
    ],
  },
  // ── appearance · interface (chat chrome) ──
  {
    id: "appearance.zenMode",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-zenMode",
    labelKey: "settings.zenMode",
    descKeys: ["settings.zenModeDesc"],
    keywords: [
      "zen",
      "focus",
      "distraction free",
      "distraction-free",
      "hide sidebar",
      "hide panes",
      "maximize chat",
      "fullscreen chat",
      "禅",
      "禪",
      "专注",
      "專注",
      "沉浸",
      "隐藏侧栏",
      "隱藏側欄",
      "最大化",
    ],
  },
  {
    id: "appearance.welcomeMotion",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-welcomeMotion",
    labelKey: "settings.welcomeMotion",
    descKeys: ["settings.welcomeMotionDesc"],
    keywords: [
      "welcome animation",
      "welcome motion",
      "new chat animation",
      "today prompt",
      "欢迎动画",
      "歡迎動畫",
      "新对话动画",
      "新對話動畫",
      "今天做什么",
      "今天做什麼",
    ],
  },
  {
    id: "appearance.thinkingExpand",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-thinkingExpand",
    labelKey: "settings.thinkingExpand",
    descKeys: [
      "settings.thinkingExpandDesc",
      "settings.thinkingExpand.autoCollapse",
      "settings.thinkingExpand.keepOpen",
    ],
    keywords: [
      "thinking",
      "reasoning",
      "collapse",
      "expand",
      "thought",
      "思考",
      "推理",
      "折叠",
      "展開",
      "展开",
    ],
  },
  {
    id: "appearance.toolStepsAutoCollapse",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-toolStepsAutoCollapse",
    labelKey: "settings.toolStepsAutoCollapse",
    descKeys: ["settings.toolStepsAutoCollapseDesc"],
    keywords: [
      "tool",
      "tools",
      "tool steps",
      "collapse",
      "auto collapse",
      "timeline",
      "activity",
      "工具",
      "工具步骤",
      "工具步驟",
      "折叠",
      "摺疊",
      "时间线",
      "時間線",
    ],
  },
  {
    id: "appearance.transcriptFilter",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-transcriptFilter",
    labelKey: "settings.transcriptFilter",
    descKeys: [
      "settings.transcriptFilterDesc",
      "settings.transcriptFilter.all",
      "settings.transcriptFilter.conversation",
    ],
    keywords: [
      "transcript",
      "filter",
      "tool steps",
      "hide tools",
      "conversation only",
      "activity",
      "timeline",
      "clean",
      "hide tool steps",
      "对话过滤",
      "對話過濾",
      "隐藏工具",
      "隱藏工具",
      "仅对话",
      "僅對話",
      "工具步骤",
      "工具步驟",
      "transcript filter",
    ],
  },
  {
    id: "appearance.uiFont",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-uiFont",
    labelKey: "settings.uiFont",
    descKeys: [
      "settings.uiFontDesc",
      "settings.uiFontHint",
      "settings.uiFontDefault",
    ],
    keywords: [
      "ui font",
      "interface font",
      "sans",
      "installed fonts",
      "dropdown",
      "system-ui",
      "界面字体",
      "介面字型",
      "本机字体",
      "本機字型",
      "字体",
      "字體",
    ],
  },
  {
    id: "appearance.terminalFont",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-terminalFont",
    labelKey: "settings.terminalFont",
    descKeys: [
      "settings.terminalFontDesc",
      "settings.terminalFontHint",
      "settings.terminalFontSize",
      "settings.terminalFontDefault",
    ],
    keywords: [
      "terminal font",
      "nerd font",
      "starship",
      "pty",
      "installed fonts",
      "dropdown",
      "终端字体",
      "終端字型",
      "本机字体",
      "本機字型",
      "Nerd Font",
    ],
  },
  {
    id: "appearance.chatFontScale",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-chatFontScale",
    labelKey: "settings.chatFontScale",
    descKeys: [
      "settings.chatFontScaleDesc",
      "settings.chatFontScale.sm",
      "settings.chatFontScale.md",
      "settings.chatFontScale.lg",
    ],
    keywords: ["font", "size", "text size", "字号", "字號", "字体", "字體"],
  },
  {
    id: "appearance.codeFontScale",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-codeFontScale",
    labelKey: "settings.codeFontScale",
    descKeys: [
      "settings.codeFontScaleDesc",
      "settings.codeFontScale.sm",
      "settings.codeFontScale.md",
      "settings.codeFontScale.lg",
    ],
    keywords: [
      "code font",
      "code size",
      "monospace",
      "pre",
      "code block",
      "代码字号",
      "程式碼字號",
      "代码字体",
      "程式碼字體",
    ],
  },
  {
    id: "appearance.chatDensity",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-chatDensity",
    labelKey: "settings.chatDensity",
    descKeys: [
      "settings.chatDensityDesc",
      "settings.chatDensity.comfortable",
      "settings.chatDensity.compact",
    ],
    keywords: [
      "density",
      "compact",
      "comfortable",
      "spacing",
      "padding",
      "dense",
      "密度",
      "紧凑",
      "緊湊",
      "舒适",
      "舒適",
      "间距",
      "間距",
    ],
  },
  {
    id: "appearance.chatWidth",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-chatWidth",
    labelKey: "settings.chatWidth",
    descKeys: [
      "settings.chatWidthDesc",
      "settings.chatWidth.narrow",
      "settings.chatWidth.medium",
      "settings.chatWidth.wide",
      "settings.chatWidth.full",
    ],
    keywords: [
      "width",
      "reading width",
      "transcript",
      "narrow",
      "medium",
      "wide",
      "full",
      "max-width",
      "column",
      "宽度",
      "寬度",
      "阅读",
      "閱讀",
      "窄",
      "中",
      "宽",
      "寬",
      "全宽",
      "全寬",
    ],
  },
  {
    id: "appearance.sidebarDensity",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-sidebarDensity",
    labelKey: "settings.sidebarDensity",
    descKeys: [
      "settings.sidebarDensityDesc",
      "settings.sidebarDensity.comfortable",
      "settings.sidebarDensity.compact",
    ],
    keywords: [
      "sidebar",
      "session list",
      "density",
      "compact",
      "comfortable",
      "spacing",
      "sessions",
      "侧栏",
      "側欄",
      "会话",
      "會話",
      "列表",
      "密度",
      "紧凑",
      "緊湊",
      "舒适",
      "舒適",
    ],
  },
  {
    id: "appearance.codeWrapDefault",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-codeWrapDefault",
    labelKey: "settings.codeWrapDefault",
    descKeys: ["settings.codeWrapDefaultDesc"],
    keywords: [
      "code wrap",
      "line wrap",
      "word wrap",
      "soft wrap",
      "代码换行",
      "自動換行",
      "自动换行",
    ],
  },
  {
    id: "appearance.codeLineNumbers",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-codeLineNumbers",
    labelKey: "settings.codeLineNumbers",
    descKeys: ["settings.codeLineNumbersDesc"],
    keywords: [
      "line numbers",
      "code lines",
      "gutter",
      "行号",
      "行號",
      "代码行号",
      "程式碼行號",
    ],
  },
  {
    id: "appearance.backBottomAlways",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-backBottomAlways",
    labelKey: "settings.backBottomAlways",
    descKeys: ["settings.backBottomAlwaysDesc"],
    keywords: [
      "back to bottom",
      "scroll to bottom",
      "always show",
      "scroll button",
      "回到底部",
      "回到最新",
      "始终显示",
      "始終顯示",
      "滚动",
      "滾動",
    ],
  },
  {
    id: "appearance.sessionSearchRank",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-sessionSearchRank",
    labelKey: "settings.sessionSearchRank",
    descKeys: [
      "settings.sessionSearchRankDesc",
      "settings.sessionSearchRank.keyword",
      "settings.sessionSearchRank.hybrid",
    ],
    keywords: [
      "session search",
      "hybrid search",
      "semantic search",
      "token overlap",
      "keyword ranking",
      "command palette",
      "include archived",
      "title content filter",
      "clear filters",
      "empty state",
      "会话搜索",
      "混合搜索",
      "语义",
      "語意",
      "关键词",
      "關鍵字",
      "词元",
      "已归档",
      "已封存",
      "筛选",
      "篩選",
      "詞元",
      "命令面板",
    ],
  },
  {
    id: "appearance.confirmExternalLinks",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-confirmExternalLinks",
    labelKey: "settings.confirmExternalLinks",
    descKeys: ["settings.confirmExternalLinksDesc"],
    keywords: [
      "external link",
      "confirm link",
      "open link",
      "http",
      "https",
      "safety",
      "外链",
      "确认",
      "確認",
      "打开链接",
      "開啟連結",
    ],
  },
  {
    id: "appearance.messageActions",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-messageActions",
    labelKey: "settings.messageActions",
    descKeys: [
      "settings.messageActionsDesc",
      "settings.messageActions.hover",
      "settings.messageActions.always",
    ],
    keywords: [
      "actions",
      "hover",
      "copy buttons",
      "message actions",
      "always show",
      "操作",
      "按钮",
      "按鈕",
      "复制",
      "複製",
    ],
  },
  {
    id: "appearance.messageTimestamps",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-messageTimestamps",
    labelKey: "settings.messageTimestamps",
    descKeys: ["settings.messageTimestampsDesc"],
    keywords: [
      "timestamp",
      "timestamps",
      "message time",
      "time label",
      "时间戳",
      "时间",
      "時間戳",
    ],
  },
  {
    id: "appearance.goalOrchUi",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-goalOrchUi",
    labelKey: "settings.goalOrchUi",
    descKeys: ["settings.goalOrchUiDesc"],
    keywords: [
      "goal",
      "orchestration",
      "classifier",
      "planner",
      "strategist",
      "verifier",
      "goal_updated",
      "reliability",
      "目标",
      "目标编排",
      "目标編排",
      "可靠性",
    ],
  },
  {
    id: "appearance.exportLogo",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-exportLogo",
    labelKey: "settings.exportLogo",
    descKeys: ["settings.exportLogoDesc"],
    keywords: [
      "export logo",
      "share card",
      "export image",
      "branding",
      "watermark",
      "custom logo",
      "导出图片",
      "导出 logo",
      "分享卡片",
      "品牌",
      "匯出圖片",
      "自訂 logo",
    ],
  },
  {
    id: "appearance.replaceProviderBrandLogo",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-replaceProviderBrandLogo",
    labelKey: "settings.replaceProviderBrandLogo",
    descKeys: ["settings.replaceProviderBrandLogoDesc"],
    keywords: [
      "replace logo",
      "brand logo",
      "provider logo",
      "sidebar logo",
      "deepseek",
      "opencode",
      "volcano",
      "volcengine",
      "ark",
      "amux",
      "替换 logo",
      "替換 logo",
      "品牌 logo",
      "服务商",
      "服務商",
      "侧栏",
      "側欄",
      "火山",
    ],
  },
  {
    id: "appearance.showReplyLength",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-showReplyLength",
    labelKey: "settings.showReplyLength",
    descKeys: ["settings.showReplyLengthDesc"],
    keywords: [
      "word count",
      "character count",
      "reply length",
      "message length",
      "chars",
      "words",
      "字数",
      "字數",
      "词数",
      "詞數",
      "回复长度",
      "回覆長度",
    ],
  },
  {
    id: "appearance.messageTimeFormat",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-messageTimeFormat",
    labelKey: "settings.messageTimeFormat",
    descKeys: [
      "settings.messageTimeFormatDesc",
      "settings.messageTimeFormat.absolute",
      "settings.messageTimeFormat.relative",
    ],
    keywords: [
      "timestamp",
      "relative",
      "relative time",
      "absolute",
      "time format",
      "ago",
      "时间戳",
      "相对时间",
      "相對時間",
      "相對",
      "相对",
    ],
  },
  {
    id: "appearance.sidebarShowRelativeTime",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-sidebarShowRelativeTime",
    labelKey: "settings.sidebarShowRelativeTime",
    descKeys: ["settings.sidebarShowRelativeTimeDesc"],
    keywords: [
      "sidebar",
      "session list",
      "relative time",
      "updated",
      "ago",
      "last active",
      "侧栏",
      "側欄",
      "会话",
      "會話",
      "相对时间",
      "相對時間",
      "更新时间",
      "更新時間",
    ],
  },
  {
    id: "appearance.sessionMuteSummary",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-sessionMuteSummary",
    labelKey: "settings.sessionMuteSummary",
    descKeys: [
      "settings.sessionMuteSummaryDesc",
      "settings.sessionMuteCount",
      "settings.sessionMuteCountZero",
      "settings.sessionMuteClear",
    ],
    keywords: [
      "mute",
      "muted",
      "notifications",
      "desktop notify",
      "unread",
      "session mute",
      "unmute",
      "静音",
      "靜音",
      "通知",
      "未读",
      "未讀",
      "会话",
      "會話",
    ],
  },
  {
    id: "appearance.sessionUnreadSummary",
    section: "appearance",
    tab: "interface",
    anchorId: "settings-anchor-sessionUnreadSummary",
    labelKey: "settings.sessionUnreadSummary",
    descKeys: [
      "settings.sessionUnreadSummaryDesc",
      "settings.sessionUnreadCount",
      "settings.sessionUnreadCountZero",
      "settings.sessionUnreadClear",
    ],
    keywords: [
      "unread",
      "read",
      "marker",
      "dot",
      "background turn",
      "clear unread",
      "未读",
      "未讀",
      "圆点",
      "圓點",
      "已读",
      "已讀",
      "会话",
      "會話",
    ],
  },
];
