import type { SettingsEntry } from "../types";

/** Settings catalog entries — remoteIm section. */
export const REMOTE_IM_ENTRIES: readonly SettingsEntry[] = [
  // ── remote_im (Remote control) ──
  {
    id: "remote_im.root",
    section: "remote_im",
    tab: "im",
    anchorId: "settings-anchor-remote-im",
    labelKey: "settings.tab.remoteIm",
    descKeys: ["settings.nav.remoteIm", "settings.remoteIm.bridgeOverview"],
    keywords: [
      "remote control",
      "remote im",
      "feishu",
      "lark",
      "telegram",
      "discord",
      "bot token",
      "message content intent",
      "gateway",
      "qq",
      "onebot",
      "napcat",
      "forward websocket",
      "matrix",
      "homeserver",
      "access token",
      "sync",
      "weibo",
      "微博",
      "app_id",
      "app_secret",
      "websocket",
      "qqbot",
      "qq official",
      "official bot",
      "gateway",
      "interaction",
      "bridge",
      "im",
      "远程控制",
      "远程 IM",
      "机器人令牌",
      "正向 WebSocket",
      "访问令牌",
      "存取權杖",
      "QQ 官方",
      "官方机器人",
    ],
  },
  {
    id: "remote_im.mirror",
    section: "remote_im",
    tab: "mirror",
    anchorId: "settings-anchor-phone-mirror",
    labelKey: "settings.tab.phoneMirror",
    descKeys: [
      "mirror.connect",
      "mirror.connectTitle",
      "mirror.connectHint",
      "mirror.maxClients",
      "mirror.cap.full",
      "mirror.cap.fullBanner",
      "mirror.cap.emptyZero",
      "mirror.write.categoriesTitle",
      "mirror.rotate",
      "mirror.phase.softLocal",
      "mirror.softLocalBanner",
      "mirror.allowLan",
      "mirror.allowLanHint",
      "mirror.linkLabelLan",
      "mirror.err.cloudflaredMissing",
      "settings.nav.remoteIm",
    ],
    keywords: [
      "phone mirror",
      "connect phone",
      "connect device",
      "qr",
      "cloudflared",
      "docker",
      "docker desktop",
      "max clients",
      "client cap",
      "503",
      "rotate token",
      "write allowlist",
      "tunnel",
      "soft fail",
      "soft-fail",
      "local only",
      "reconnecting",
      "lan",
      "wifi",
      "wi-fi",
      "same network",
      "手机镜像",
      "连接手机",
      "连接设备",
      "最大连接",
      "连接上限",
      "重新生成",
      "隧道",
      "仅本机",
      "软失败",
      "局域网",
      "同一 Wi-Fi",
    ],
  },
];
